"""GlowAgent_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFsF3kWgQYqMPjjJxXRiZ8jVCx1MohMg

# GlowAgent

---
GlowAgent is an AI skincare assistant designed for 18–24 year olds in the U.S. who want effective skincare recommendations without spending hours researching products or exceeding their budget. The agent collects structured user input such as skin type, concerns, allergies, current routine, and budget combines it with product ingredient databases and real-time web data to generate personalized, budget-conscious skincare routines.
---
"""

# Configure API keys

import os
from dotenv import load_dotenv

load_dotenv()

"""#STEP 1: Load in the ingredient and product databases"""

# Document Loading

from pathlib import Path
import pandas as pd

# paths of the csv files
BASE_DIR = Path(__file__).resolve().parent.parent
ingredients_csv_path = BASE_DIR / "data" / "skincare_ingredients.csv"
products_csv_path = BASE_DIR / "data" / "skincare_products.csv"

# Load CSVs
ingredients_df = pd.read_csv(ingredients_csv_path)
products_df = pd.read_csv(products_csv_path)

'''
# Inspect the ingredients dataset
print("------Skincare Ingredients Dataset--------")
print("Columns in the database: ", ingredients_df.columns.tolist())
print("Number of Ingredients(rows): ", len(ingredients_df))
print("First 5 rows: ",ingredients_df.head())
'''

# Clean ingredients dataset

# Drop the scientific name columns from the ingredients database as it has only null values
ingredients_df = ingredients_df.dropna(axis=1, how='all')

# Fill missing text fields
ingredient_text_cols = ['name', 'short_description', 'what_is_it', 'what_does_it_do',
                        'who_is_it_good_for', 'who_should_avoid', 'url']
for col in ingredient_text_cols:
    if col in ingredients_df.columns:
        ingredients_df[col] = ingredients_df[col].fillna('Unknown')

'''
# Inspect the products dataset
print("------Skincare products Dataset--------")
print("Columns in the database: ", products_df.columns.tolist())
print("Number of Products(rows): ", len(products_df))
print("first five rows: ",products_df.head())
'''

# Clean products dataset

# Drop empty columns
products_df = products_df.dropna(axis=1, how='all')

# Fill missing text fields
product_text_cols = ['product_name', 'product_type', 'brand', 'notable_effects', 'skintype', 'product_href', 'picture_src']
for col in product_text_cols:
    if col in products_df.columns:
        products_df[col] = products_df[col].fillna('Unknown')

# Combine boolean skin type columns into a single string
skin_cols = ['Sensitive', 'Combination', 'Oily', 'Dry', 'Normal']
for col in skin_cols:
    if col in products_df.columns:
        products_df[col] = products_df[col].fillna(0)  # fill missing booleans with 0

products_df['skin_types_str'] = products_df[skin_cols].apply(
    lambda row: ", ".join([col for col in skin_cols if row[col] == 1]),
    axis=1
)
products_df['skin_types_str'] = products_df['skin_types_str'].replace('', 'Unknown')

"""# STEP 2: Chunking"""

def format_ingredient_row(row):
    return (
        f"Ingredient: {row['name']}\n"
        f"Short Description: {row['short_description']}\n"
        f"What It Is: {row['what_is_it']}\n"
        f"What It Does: {row['what_does_it_do']}\n"
        f"Who It Is Good For: {row['who_is_it_good_for']}\n"
        f"Who Should Avoid: {row['who_should_avoid']}\n"
        f"More Info: {row['url']}\n"
        f"Source: GlowAgent ingredient dataset"
    )

def format_product_row(row):
    return (
        f"Product: {row['product_name']}\n"
        f"Brand: {row['brand']}\n"
        f"Category: {row['product_type']}\n"
        f"Effects: {row['notable_effects']}\n"
        f"Skin Types: {row['skin_types_str']}\n"
        f"More Info: {row['product_href']}\n"
        f"Source: GlowAgent product dataset"
    )

ingredient_chunks = [format_ingredient_row(row) for _, row in ingredients_df.iterrows()]
product_chunks = [format_product_row(row) for _, row in products_df.iterrows()]

all_chunks = product_chunks + ingredient_chunks
'''
print("Total chunks created:", len(all_chunks))
print(all_chunks[:2])  # preview first 2 chunks
'''

"""# Step 3: LLM setup"""

from langchain_google_genai import ChatGoogleGenerativeAI

# Create the LLM with model gemini-2.0-flash
llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    google_api_key=os.environ.get("GOOGLE_API_KEY")
)

"""# STEP 4: Embedding Setup"""

# Embedding

from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma

embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-001"
)

"""# STEP 5: Storing in vector database"""

vectorstore = Chroma.from_texts(
    texts=all_chunks,
    embedding=embeddings
)

# print("Vector database created with", vectorstore._collection.count(), "documents")

"""# STEP 6: Tools"""

from langchain_core.tools import tool
from langchain_tavily import TavilySearch
from langchain.agents import create_agent

"""### a)  Database search tool"""
@tool
def skincare_database_search(query: str) -> str:
    """
    Search the GlowAgent skincare product and ingredient database.

    Use this tool for any question about:
    - Specific skincare product recommendations
    - Skin type matching (oily, dry, combination, sensitive)
    - Budget-based filtering (e.g. under $20)
    - Product categories (cleanser, moisturizer, serum, sunscreen, toner)
    - Ingredient lists for products in the local database

    Use this tool as the default starting point for recommendation-style
    skincare queries when the answer may exist in the local database.

    Do NOT use this tool when:
    - The product is likely niche, international, or not in the local database
    - The user is asking for real-time web information such as current price or availability

    If the result is incomplete or missing, use `open_beauty_facts_search`
    to verify ingredients or search a broader external cosmetics database.
    Use `tavily_search_tool` for current web information such as price of the product,
    retailer availability, or recent product details.

    Input: a natural language query such as "moisturizer for oily skin under $20"
    or "cleanser with salicylic acid for acne".

    Returns: up to 4 matching product names, brands, categories, prices,
    ratings, skin type suitability, and ingredient lists.
    """

    docs = vectorstore.similarity_search(query, k=4)
    if not docs:
        return "No matching skincare products found."
    return "\n\n---\n\n".join(doc.page_content for doc in docs)

"""### b) Open Beauty Facts Search Tool"""
import time
from langchain_core.tools import tool
from openfoodfacts import API, APIVersion, Country, Environment, Flavor

# Initialize the Open Beauty Facts API client
# No API key required — fully open database
obf_api = API(
    user_agent="GlowAgent/1.0",
    country=Country.world,
    flavor=Flavor.obf,          # obf = Open BEAUTY Facts
    version=APIVersion.v2,
    environment=Environment.org,
)

# print("Open Beauty Facts API client ready.")

def format_obf_product(p: dict) -> str:
    """Convert a raw Open Beauty Facts product dict into a clean text passage."""
    name       = p.get('product_name') or p.get('generic_name') or 'Unknown'
    brand      = p.get('brands', 'Unknown')
    categories = p.get('categories', 'Unknown')
    quantity   = p.get('quantity', 'N/A')
    barcode    = p.get('code', 'N/A')
    ingredients = (
        p.get('ingredients_text_en')
        or p.get('ingredients_text')
        or 'Not listed'
    )
    if len(ingredients) > 500:
        ingredients = ingredients[:497] + '...'
    allergens = p.get('allergens', '') or p.get('allergens_tags', '')
    if isinstance(allergens, list):
        allergens = ', '.join(allergens) or 'None listed'
    allergens = allergens or 'None listed'
    return (
        f"[Open Beauty Facts]\n"
        f"Product: {name} | Brand: {brand}\n"
        f"Category: {categories} | Size: {quantity} | Barcode: {barcode}\n"
        f"Ingredients: {ingredients}\n"
        f"Allergens: {allergens}\n"
        f"Source: Open Beauty Facts (world.openbeautyfacts.org)"
    )

@tool
def open_beauty_facts_search(query: str) -> str:
    """
    Search the Open Beauty Facts database — a crowd-sourced global database
    of cosmetic and personal care products.

    Use this tool when you need:
    - Full verified INCI ingredient lists for a specific product
    - Allergen information (e.g. does this product contain parabens?)
    - Products not found in the local skincare database
    - International or niche cosmetic brands
    - Cross-checking whether a product contains certain ingredients

    Do NOT use this tool for:
    - Real-time product prices
    - Current promotional or commercial web information

    If the user asks for current price, availability, or other live web data,
    use `tavily_search_tool` with the product name.

    Input: a product name, brand, or ingredient keyword
    (e.g. "La Roche-Posay Toleriane cleanser" or "vitamin C serum").

    Returns: up to 4 matching products with full ingredient lists,
    allergens, brand, category, and barcode.
    """
    try:
        time.sleep(1)  # Respect 10 req/min rate limit
        results  = obf_api.product.text_search(query, page_size=4, page=1)
        products = results.get('products', [])
        if not products:
            return f"No products found in Open Beauty Facts for: '{query}'"
        formatted = [
            format_obf_product(p) for p in products
            if p.get('product_name') or p.get('generic_name')
        ]
        if not formatted:
            return f"Products found but all had incomplete data for: '{query}'"
        header = f"Open Beauty Facts: {len(formatted)} result(s) for '{query}':\n"
        return header + "\n\n---\n\n".join(formatted)
    except Exception as e:
        return f"Open Beauty Facts API error: {str(e)}"

"""### c) Tavily as generel search tool for pricing"""
import os
import re
import json
from tavily import TavilyClient
from langchain_core.tools import tool
from langchain_tavily import TavilySearch

# Setup the TavilySearch tool
tavily_search = TavilySearch(
    max_results=4,
    search_depth="basic",
    include_answer=True,
    include_raw_content=False
)

def extract_price(text):
    """
    Extracts USD price from text, handles $12, $12.99, $1,299.00 formats.
    """
    match = re.search(r"\$\s?\d{1,3}(?:,\d{3})*(?:\.\d{2})?", text)
    return match.group() if match else None

def extract_discount(text):
    """
    Extracts discount information like '20% off', 'Save $10', etc.
    """
    match = re.search(r"(\d{1,3}%\s?off|Save\s?\$\d+(?:\.\d{2})?)", text, re.IGNORECASE)
    return match.group() if match else None

@tool
def tavily_search_tool(product: str) -> str:
    """
    Search the web for live or recent skincare-related information.

    Best for:
    - Current product prices
    - Retailer listings and shopping pages
    - Availability information
    - Recent web content about a product or brand
    - Filling gaps when the local database and Open Beauty Facts
      do not provide enough information

    Use this tool when the user asks for real-time or web-based information,
    such as:
    - "How much does this product cost?"
    - "Where can I buy this?"
    - "Is this product available at Sephora or Ulta?"
    - "What are people saying about this product recently?"

    Do NOT use this tool as the first choice for ingredient verification
    if the information may already exist in the local database or
    Open Beauty Facts.

    Input: a product name, brand, or web search query such as
    "CeraVe PM Facial Moisturizing Lotion price" or
    "Best fragrance-free sunscreen under $20"

    Returns: relevant web search results and summaries from recent sources.
    """

    # Focus search on popular online retailers
    query = f'"{product}" price discount (site:ulta.com OR site:sephora.com OR site:amazon.com OR site:walmart.com OR site:target.com)'

    # Invoke TavilySearch
    results = tavily_search.invoke({"query": query})

    prices = []

    # Loop through results and extract price/discount
    for r in results.get("results", []):
        content = r.get("content") or r.get("answer") or ""
        price = extract_price(content)
        discount = extract_discount(content)

        if price:
            prices.append({
                "product": r.get("title", "Unknown Product"),
                "price": price,
                "discount": discount or "N/A",
                "url": r.get("url", "N/A")
            })

    if not prices:
        return f"No price or discount found for '{product}'."

    return json.dumps(prices, indent=2)

'''
# --- Test the tool ---
result = tavily_search_tool("Neutrogena sunscreen")
print(result)
'''

"""### e) Ranking tool"""

# Enter the code for ranking tool

"""### f) Notification tool"""

# Enter the code for notifcation tool

"""# STEP 7: Generation -- Build and Test the Multi-Tool Agent"""

# System prompt — tells the agent WHEN to use each tool
multi_tool_prompt = """You are GlowAgent, an AI-powered skincare assistant designed
for U.S.-based users aged 18–24 who want effective, budget-friendly skincare
recommendations. Your role is to act as a non-diagnostic, educational skincare
guide that helps users build, evaluate, and optimize their routines.

You have three tools. Use them in this priority order:

1. skincare_database_search
   USE FOR: Initial product recommendations, skin-type matching, budget filtering,
   product categories (cleanser, moisturizer, serum, sunscreen).
   Always try this tool FIRST.

2. open_beauty_facts_search
   USE FOR: Verifying full ingredient lists, allergen checks (parabens, fragrance,
   sulfates), products not in the local database, or when a user asks what
   is in a specific named product.

3. tavily_search
   USE FOR: Current prices, trending products, recent reviews, new launches,
   or any information that changes frequently.
   Use this LAST, or when the first two tools don't have enough information.

When giving skincare routine recommendations:
- Organize by step: Cleanser → Treatment → Moisturizer → Sunscreen
- For each product include: name, brand, why it suits the concern,
  price, skin type suitability, and any allergen flags
- Suggest a lower-cost alternative when possible
- End with a short summary, safety notes, and reassessment timeline (6–8 weeks)

Keep explanations clear, concise, and educational — not overly clinical.
"""

agent = create_agent(
    llm,
    tools=[skincare_database_search, open_beauty_facts_search, tavily_search_tool],
    system_prompt=multi_tool_prompt
)

"""# Step 8: Query the agent"""

'''
# Test query 1 (expected: skincare database tool)
query_1 = "Recommend a moisturizer for dry sensitive skin under $20."

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_1}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 2 (expected: ingredient lookup tool)
query_2 = "What ingredients are in CeraVe Moisturizing Cream? Does it contain parabens?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_2}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 3 (expected: price search tool)
query_3 = "How much does The Ordinary Niacinamide 10% + Zinc 1% cost right now?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_3}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 4 (expected: skincare database + ingredient verification)
query_4 = "Build me a skincare routine for oily acne-prone skin under $30 and make sure none of the products contain fragrance."

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_4}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 5 (expected: Tavily web search)
query_5 = "What are the most popular drugstore skincare products in 2025?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_5}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()
'''


"""Must-Have Tools

1. **skincare_database_search**

*  Retrieves skincare products from your dataset.
*  Core tool for product recommendations.


2. **open_beauty_facts_search**

*   Fetches ingredient information.
*   Helps verify product safety and ingredients.

3. **tavily_price_search**

*   Finds real-time prices and discounts online.
*   Important for affordable skincare recommendations.

4. **product_ranking_tool**

*   Ranks products (best → second best → third best)
*   Helps the agent choose the most suitable product.

5. **routine_builder_tool**- Converts recommendations into a complete skincare routine.

Good to Add

6. **ingredient_safety_checker**- Flags harmful or irritating ingredients.

7. **skin_image_analysis**- Lets users upload a photo to detect skin issues.

Optional

8. **budget_optimizer_tool**- Suggests cheaper alternatives.

9. **notification_tool**- Sends skincare reminders.

10. **user_profile_manager**- Stores user preferences (skin type, allergies, budget).

"""