"""GlowAgent_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FFsF3kWgQYqMPjjJxXRiZ8jVCx1MohMg

# GlowAgent

---
GlowAgent is an AI skincare assistant designed for 18–24 year olds in the U.S. who want effective skincare recommendations without spending hours researching products or exceeding their budget. The agent collects structured user input such as skin type, concerns, allergies, current routine, and budget combines it with product ingredient databases and real-time web data to generate personalized, budget-conscious skincare routines.
---
"""

# Configure API keys

import os
from dotenv import load_dotenv

load_dotenv()

"""# STEP 1: Load in the ingredient and product databases"""

# Document Loading
from pathlib import Path
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import Chroma
from app.build_vectorstore import load_products_df

# only load the existing Chroma DB when the app starts up
BASE_DIR = Path(__file__).resolve().parent.parent
CHROMA_PERSIST_DIR = BASE_DIR / "chroma_db"

embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")

vectorstore = Chroma(
    persist_directory=str(CHROMA_PERSIST_DIR),
    embedding_function=embeddings,
    collection_name="glowagent_skincare",
)

import pandas as pd

products_df = load_products_df()

_product_image_by_name = dict(zip(products_df["product_name"], products_df["picture_src"]))

def _enrich_product_doc_with_image(page_content: str) -> str:
    """Insert Image: URL after More Info when the product exists in the local CSV (vector chunks may omit it)."""
    if "Image:" in page_content:
        return page_content
    name = None
    for line in page_content.split("\n"):
        if line.startswith("Product:"):
            name = line.replace("Product:", "").strip()
            break
    if not name:
        return page_content
    pic = _product_image_by_name.get(name)
    if not pic or str(pic) in ("Unknown", "nan") or not str(pic).startswith("http"):
        return page_content
    lines = page_content.split("\n")
    out = []
    inserted = False
    for line in lines:
        out.append(line)
        if not inserted and line.startswith("More Info:"):
            out.append(f"Image: {pic}")
            inserted = True
    if not inserted:
        out.append(f"Image: {pic}")
    return "\n".join(out)

"""# STEP 2: Set up short term memory"""

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.prebuilt import create_react_agent

checkpointer = InMemorySaver()

"""# STEP 3: LLM setup"""

from langchain_google_genai import ChatGoogleGenerativeAI

# Create the LLM with model gemini-2.0-flash
llm = ChatGoogleGenerativeAI(
    model="gemini-2.0-flash",
    google_api_key=os.environ.get("GOOGLE_API_KEY")
)

"""# STEP 6: Tools"""

from langchain_core.tools import tool
from langchain_tavily import TavilySearch

"""### Database search tool"""
@tool
def skincare_database_search(query: str) -> str:
    """
    Search the GlowAgent skincare product and ingredient database.

    Use this tool for any question about:
    - Specific skincare product recommendations
    - Skin type matching (oily, dry, combination, sensitive)
    - Budget-based filtering (e.g. under $20)
    - Product categories (cleanser, moisturizer, serum, sunscreen, toner)
    - Ingredient lists for products in the local database

    Use this tool as the default starting point for recommendation-style
    skincare queries when the answer may exist in the local database.

    Do NOT use this tool when:
    - The product is likely niche, international, or not in the local database
    - The user is asking for real-time web information such as current price or availability

    If the result is incomplete or missing, use `open_beauty_facts_search`
    to verify ingredients or search a broader external cosmetics database.
    Use `tavily_search_tool` for current web information such as price of the product,
    retailer availability, or recent product details.

    Input: a natural language query such as "moisturizer for oily skin under $20"
    or "cleanser with salicylic acid for acne".

    Returns: up to 4 matching product names, brands, categories, prices,
    ratings, skin type suitability, and ingredient lists.
    """

    docs = vectorstore.similarity_search(query, k=4)
    if not docs:
        return "No matching skincare products found."
    enriched = [_enrich_product_doc_with_image(doc.page_content) for doc in docs]
    return "\n\n---\n\n".join(enriched)

"""### Open Beauty Facts Search Tool"""
import time
from langchain_core.tools import tool
from openfoodfacts import API, APIVersion, Country, Environment, Flavor

# Initialize the Open Beauty Facts API client
# No API key required — fully open database
obf_api = API(
    user_agent="GlowAgent/1.0",
    country=Country.world,
    flavor=Flavor.obf,          # obf = Open BEAUTY Facts
    version=APIVersion.v2,
    environment=Environment.org,
)

# print("Open Beauty Facts API client ready.")

def format_obf_product(p: dict) -> str:
    """Convert a raw Open Beauty Facts product dict into a clean text passage."""
    name       = p.get('product_name') or p.get('generic_name') or 'Unknown'
    brand      = p.get('brands', 'Unknown')
    categories = p.get('categories', 'Unknown')
    quantity   = p.get('quantity', 'N/A')
    barcode    = p.get('code', 'N/A')
    ingredients = (
        p.get('ingredients_text_en')
        or p.get('ingredients_text')
        or 'Not listed'
    )
    if len(ingredients) > 500:
        ingredients = ingredients[:497] + '...'
    allergens = p.get('allergens', '') or p.get('allergens_tags', '')
    if isinstance(allergens, list):
        allergens = ', '.join(allergens) or 'None listed'
    allergens = allergens or 'None listed'
    return (
        f"[Open Beauty Facts]\n"
        f"Product: {name} | Brand: {brand}\n"
        f"Category: {categories} | Size: {quantity} | Barcode: {barcode}\n"
        f"Ingredients: {ingredients}\n"
        f"Allergens: {allergens}\n"
        f"Source: Open Beauty Facts (world.openbeautyfacts.org)"
    )

@tool
def open_beauty_facts_search(query: str) -> str:
    """
    Search the Open Beauty Facts database — a crowd-sourced global database
    of cosmetic and personal care products.

    Use this tool when you need:
    - Full verified INCI ingredient lists for a specific product
    - Allergen information (e.g. does this product contain parabens?)
    - Products not found in the local skincare database
    - International or niche cosmetic brands
    - Cross-checking whether a product contains certain ingredients

    Do NOT use this tool for:
    - Real-time product prices
    - Current promotional or commercial web information

    If the user asks for current price, availability, or other live web data,
    use `tavily_search_tool` with the product name.

    Input: a product name, brand, or ingredient keyword
    (e.g. "La Roche-Posay Toleriane cleanser" or "vitamin C serum").

    Returns: up to 4 matching products with full ingredient lists,
    allergens, brand, category, and barcode.
    """
    try:
        time.sleep(1)  # Respect 10 req/min rate limit
        results  = obf_api.product.text_search(query, page_size=4, page=1)
        products = results.get('products', [])
        if not products:
            return f"No products found in Open Beauty Facts for: '{query}'"
        formatted = [
            format_obf_product(p) for p in products
            if p.get('product_name') or p.get('generic_name')
        ]
        if not formatted:
            return f"Products found but all had incomplete data for: '{query}'"
        header = f"Open Beauty Facts: {len(formatted)} result(s) for '{query}':\n"
        return header + "\n\n---\n\n".join(formatted)
    except Exception as e:
        return f"Open Beauty Facts API error: {str(e)}"

"""### Tavily as general search tool for pricing"""
import os
import re
import json
from tavily import TavilyClient
from langchain_core.tools import tool
from langchain_tavily import TavilySearch

# Setup the TavilySearch tool
tavily_search = TavilySearch(
    max_results=4,
    search_depth="basic",
    include_answer=True,
    include_raw_content=False
)

def extract_price(text):
    """
    Extracts USD price from text, handles $12, $12.99, $1,299.00 formats.
    """
    match = re.search(r"\$\s?\d{1,3}(?:,\d{3})*(?:\.\d{2})?", text)
    return match.group() if match else None

def extract_discount(text):
    """
    Extracts discount information like '20% off', 'Save $10', etc.
    """
    match = re.search(r"(\d{1,3}%\s?off|Save\s?\$\d+(?:\.\d{2})?)", text, re.IGNORECASE)
    return match.group() if match else None

@tool
def tavily_search_tool(product: str) -> str:
    """
    Search the web for live or recent skincare-related information.

    Best for:
    - Current product prices
    - Retailer listings and shopping pages
    - Availability information
    - Recent web content about a product or brand
    - Filling gaps when the local database and Open Beauty Facts
      do not provide enough information

    Use this tool when the user asks for real-time or web-based information,
    such as:
    - "How much does this product cost?"
    - "Where can I buy this?"
    - "Is this product available at Sephora or Ulta?"
    - "What are people saying about this product recently?"

    Do NOT use this tool as the first choice for ingredient verification
    if the information may already exist in the local database or
    Open Beauty Facts.

    Input: a product name, brand, or web search query such as
    "CeraVe PM Facial Moisturizing Lotion price" or
    "Best fragrance-free sunscreen under $20"

    Returns: relevant web search results and summaries from recent sources.
    """

    # Focus search on popular online retailers
    query = f'"{product}" price discount (site:ulta.com OR site:sephora.com OR site:amazon.com OR site:walmart.com OR site:target.com)'

    # Invoke TavilySearch
    results = tavily_search.invoke({"query": query})

    prices = []

    # Loop through results and extract price/discount
    for r in results.get("results", []):
        content = r.get("content") or r.get("answer") or ""
        price = extract_price(content)
        discount = extract_discount(content)

        if price:
            prices.append({
                "product": r.get("title", "Unknown Product"),
                "price": price,
                "discount": discount or "N/A",
                "url": r.get("url", "N/A")
            })

    if not prices:
        return f"No price or discount found for '{product}'."

    return json.dumps(prices, indent=2)

'''
# --- Test the tool ---
result = tavily_search_tool("Neutrogena sunscreen")
print(result)
'''

"""### Product Ranking Tool

The product ranking tool scores and ranks skincare products from the local
database based on the user's skin type, concerns, and product category.
It helps the agent choose the best options (1st, 2nd, 3rd, etc.) when
presenting recommendations.
"""

# Map user-friendly product terms to dataset product_type values
PRODUCT_TYPE_ALIASES = {
    "cleanser": ["Face Wash", "Cleanser"],
    "face wash": ["Face Wash"],
    "moisturizer": ["Moisturizer", "Face Cream", "Lotion"],
    "serum": ["Serum", "Essence"],
    "sunscreen": ["Sunscreen", "SPF"],
    "toner": ["Toner"],
    "treatment": ["Serum", "Treatment"],
}

def _score_product_for_ranking(row, skin_type: str, concerns: str, product_type_filter: str) -> float:
    """
    Score a single product (0-100) based on how well it matches user criteria.
    Higher score = better match.
    """
    score = 0.0

    # 1. Skin type match (products have Sensitive, Combination, Oily, Dry, Normal)
    if skin_type:
        skin_lower = skin_type.lower().strip()
        skin_cols = ["Sensitive", "Combination", "Oily", "Dry", "Normal"]
        for col in skin_cols:
            if col.lower() in skin_lower and col in row.index:
                if row.get(col, 0) == 1:
                    score += 15  # Strong match for stated skin type
                break
        # Also check skintype string column (e.g. "Normal, Dry, Oily")
        skintype_str = str(row.get("skintype", "")).lower()
        if skintype_str and any(s in skintype_str for s in skin_lower.split()):
            score += 10

    # 2. Effects/concerns match (notable_effects: "Acne-Free, Pore-Care, Brightening")
    if concerns:
        effects = str(row.get("notable_effects", "")).lower()
        for concern in concerns.lower().split(","):
            concern = concern.strip()
            if not concern:
                continue
            # Map common concerns to effect keywords
            concern_map = {
                "acne": ["acne", "pore", "purifying", "clarifying"],
                "pores": ["pore", "pore-care", "refining"],
                "dryness": ["moisturizing", "hydration", "hydrating", "dry"],
                "sensitivity": ["soothing", "sensitive", "calming", "gentle"],
                "dark spots": ["brightening", "hyperpigmentation", "even"],
                "aging": ["anti-aging", "wrinkle", "firming"],
                "oil": ["oil-control", "balancing", "matifying"],
            }
            keywords = concern_map.get(concern, [concern])
            if any(kw in effects for kw in keywords):
                score += 12

    # 3. Product type/category match
    if product_type_filter:
        pt_lower = product_type_filter.lower().strip()
        row_pt = str(row.get("product_type", "")).lower()
        matched = False
        for alias, types in PRODUCT_TYPE_ALIASES.items():
            if alias in pt_lower:
                if any(t.lower() in row_pt for t in types):
                    score += 20  # Strong match for category
                matched = True
                break
        if not matched and pt_lower in row_pt:
            score += 20  # Direct substring match

    # 4. Base relevance
    return max(0, min(100, score + 5))

@tool
def product_ranking_tool(
    query: str,
    skin_type: str = "",
    concerns: str = "",
    product_type: str = "",
    allergies: str = "",
    max_results: int = 5,
) -> str:
    """
    Rank skincare products from the GlowAgent database by relevance to the user.

    Use this tool when you have a recommendation scenario and want to present
    the best options in order (1st choice, 2nd choice, etc.). Call this AFTER
    skincare_database_search when you need to prioritize specific products, or
    use it directly when the user asks for "top/best X products for Y".

    Inputs:
    - query: Natural language search (e.g. "moisturizer for oily acne-prone skin")
    - skin_type: User's skin type: oily, dry, combination, sensitive, normal
    - concerns: User's skin concerns (comma-separated): acne, pores, dryness, etc.
    - product_type: Category filter: cleanser, moisturizer, serum, sunscreen, toner
    - allergies: Ingredients to avoid (comma-separated): fragrance, niacinamide
    - max_results: How many top products to return (default 5)

    Returns: A ranked list of products with name, brand, category, effects,
    skin types, link, and image URL when available — best match first.
    """
    # Filter out products that contain allergy terms
    allergy_terms = [a.strip().lower() for a in allergies.split(",") if a.strip()]
    candidates = products_df.copy()

    for term in allergy_terms:
        mask = (
            candidates["product_name"].str.lower().str.contains(term, na=False)
            | candidates["notable_effects"].str.lower().str.contains(term, na=False)
        )
        candidates = candidates[~mask]

    if candidates.empty:
        return f"No products found that avoid: {allergies}. Try broadening your search."

    # Score each candidate
    candidates["_rank_score"] = candidates.apply(
        lambda row: _score_product_for_ranking(row, skin_type, concerns, product_type),
        axis=1,
    )

    # Boost score for products retrieved by semantic search (query)
    if query.strip():
        try:
            docs = vectorstore.similarity_search(query, k=20)
            retrieved_names = set()
            for doc in docs:
                for line in doc.page_content.split("\n"):
                    if line.startswith("Product:"):
                        name = line.replace("Product:", "").strip()
                        if name:
                            retrieved_names.add(name)
            def boost_from_retrieval(row):
                base = row["_rank_score"]
                if row["product_name"] in retrieved_names:
                    return base + 25
                return base

            candidates["_rank_score"] = candidates.apply(boost_from_retrieval, axis=1)
        except Exception:
            pass

    # Sort by score descending, take top N
    ranked = candidates.nlargest(max_results, "_rank_score")
    ranked = ranked.drop(columns=["_rank_score"], errors="ignore")

    if ranked.empty:
        return "No matching products found. Try adjusting filters or product type."

    # Format output for the agent
    lines = []
    for i, (_, row) in enumerate(ranked.iterrows(), 1):
        block = (
            f"{i}. {row['product_name']} ({row['brand']})\n"
            f"   Category: {row['product_type']} | Effects: {row['notable_effects']}\n"
            f"   Skin types: {row['skin_types_str']}\n"
            f"   Link: {row['product_href']}"
        )
        pic = row.get("picture_src", "")
        if pic and str(pic) not in ("Unknown", "nan") and str(pic).startswith("http"):
            block += f"\n   Image: {pic}"
        lines.append(block)
    return "\n\n".join(lines)

"""### Notification tool"""

# Enter the code for notifcation tool

"""# STEP 7: Generation -- Build and Test the Multi-Tool Agent"""

# System prompt — tells the agent WHEN to use each tool
multi_tool_prompt = """You are GlowAgent, an AI-powered skincare assistant designed
for U.S.-based users aged 18–24 who want effective, budget-friendly skincare
recommendations. Your role is to act as a non-diagnostic, educational skincare
guide that helps users build, evaluate, and optimize their routines.

You have four tools. Use them in this priority order:

1. skincare_database_search
   USE FOR: Initial product recommendations, skin-type matching, budget filtering,
   product categories (cleanser, moisturizer, serum, sunscreen).
   Always try this tool FIRST.

2. product_ranking_tool
   USE FOR: Ranking products by relevance when the user wants "best", "top 3",
   or prioritized options. Call with query + skin_type + concerns + product_type
   + allergies to get products ordered best-to-worst. Use after or instead of
   skincare_database_search when ordering matters.

3. open_beauty_facts_search
   USE FOR: Verifying full ingredient lists, allergen checks (parabens, fragrance,
   sulfates), products not in the local database, or when a user asks what
   is in a specific named product.

4. tavily_search_tool
   USE FOR: Current prices, trending products, recent reviews, new launches,
   or any information that changes frequently.
   Use this LAST, or when the first two tools don't have enough information.

When giving skincare routine recommendations:
- Organize by step: Cleanser → Treatment → Moisturizer → Sunscreen
- For each product include: name, brand, why it suits the concern,
  price, skin type suitability, and any allergen flags
- Suggest a lower-cost alternative when possible
- End with a short summary, safety notes, and reassessment timeline (6–8 weeks)

When tools return products from the GlowAgent database, preserve each product's
Link and Image lines (and "More Info" + Image from skincare_database_search)
exactly as returned so the chat UI can show thumbnails and clickable product pages.

Keep explanations clear, concise, and educational — not overly clinical.
"""

agent = create_react_agent(
    llm,
    tools=[skincare_database_search, product_ranking_tool, open_beauty_facts_search, tavily_search_tool],
    prompt=multi_tool_prompt,
    checkpointer=checkpointer
)

"""# Step 8: Query the agent"""

'''
# Test query 1 (expected: skincare database tool)
query_1 = "Recommend a moisturizer for dry sensitive skin under $20."

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_1}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 2 (expected: ingredient lookup tool)
query_2 = "What ingredients are in CeraVe Moisturizing Cream? Does it contain parabens?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_2}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 3 (expected: price search tool)
query_3 = "How much does The Ordinary Niacinamide 10% + Zinc 1% cost right now?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_3}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 4 (expected: skincare database + ingredient verification)
query_4 = "Build me a skincare routine for oily acne-prone skin under $30 and make sure none of the products contain fragrance."

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_4}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()

# Test query 5 (expected: Tavily web search)
query_5 = "What are the most popular drugstore skincare products in 2025?"

for chunk in multi_tool_agent.stream(
    {"messages": [{"role": "human", "content": query_5}]},
    stream_mode="updates"
):
    for step, data in chunk.items():
        print(f"Step: {step}")
        print(f"Content: {data['messages'][-1].content_blocks}")
        print()
'''


"""Must-Have Tools

1. **skincare_database_search**

*  Retrieves skincare products from your dataset.
*  Core tool for product recommendations.


2. **open_beauty_facts_search**

*   Fetches ingredient information.
*   Helps verify product safety and ingredients.

3. **tavily_price_search**

*   Finds real-time prices and discounts online.
*   Important for affordable skincare recommendations.

4. **product_ranking_tool**

*   Ranks products (best → second best → third best)
*   Helps the agent choose the most suitable product.

5. **routine_builder_tool**- Converts recommendations into a complete skincare routine.

Good to Add

6. **ingredient_safety_checker**- Flags harmful or irritating ingredients.

7. **skin_image_analysis**- Lets users upload a photo to detect skin issues.

Optional

8. **budget_optimizer_tool**- Suggests cheaper alternatives.

9. **notification_tool**- Sends skincare reminders.

10. **user_profile_manager**- Stores user preferences (skin type, allergies, budget).

"""